name: Deploy to AWS EC2

on:
  push:
    branches:
      - main   # déclenché à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/projet-churn
            git pull origin main
            pip3 install -r requirements.txt --break-system-packages
            sudo systemctl restart churn
            echo "✅ Déploiement réussi"
