name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 20m
          script: |
            sudo chown -R ec2-user:ec2-user /home/ec2-user/projet-churn
            git config --global --add safe.directory /home/ec2-user/projet-churn
            cd /home/ec2-user/projet-churn
            git reset --hard origin/main
            git pull origin main
            pip3 install -r streamlit/requirements.txt
            pkill -f streamlit || true
            sleep 2
            setsid nohup streamlit run streamlit/app.py \
              --server.port 8501 \
              --server.address 0.0.0.0 \
              > /home/ec2-user/streamlit.log 2>&1 < /dev/null &
            echo "✅ Déploiement réussi"
